baseURL = 'https://mullins.pro/'
languageCode = 'en-us'
title = 'Mullins Thoughts'
theme = 'hugo-coder'
enableEmoji = true

buildDrafts = false
buildFuture = false
buildExpired = false
paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 2

[params]
  author = "Matthew Mullins"
  description = "Public musings..."
  avatarURL = "images/headshot.png"
  keywords = "blog,personal,data,analytics,engineering,product"
  info = ["Product and Engineering for Data"]
  colorScheme = "auto"
  hidecolorschemetoggle = false
  
  env = "production"
  ShowShareButtons = true
  ShowReadingTime = true
  displayFullLangName =  true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true

  [[params.social]]
    icon = "fa-brands fa-linkedin fa-2x"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/msmullins/"
  [[params.social]]
    icon = "fa-brands fa-threads fa-2x"
    name = "LinkedIn"
    url = "https://www.threads.net/@matthew_mullins_"
  [[params.social]]
    icon = "fa-brands fa-github fa-2x"
    name = "Github"
    url = "https://github.com/msmullins"
  [[params.social]]
    name = "RSS"
    icon = "fa-solid fa-rss fa-2x"
    weight = 4
    url = "https://mullins.pro/index.xml"
    rel = "alternate"
    type = "application/rss+xml"
