baseURL = 'https://mullins.pro/'
languageCode = 'en-us'
title = 'Mullins Thought'
theme = 'PaperMod'
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true

[outputs]
home = ['html', 'json', 'rss']
page = ['html', 'rss']

[params]
author = "Matthew Mullins"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName =  true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true

[[params.fuseOpts]]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
   # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
keys = ["title", "permalink", "summary", "content"]

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/msmullins/"
